### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by qjouda** [manshar/manshar#172]
- [x] New article form: the fields overlap when using Firefox ( FF 35.0.1, Ubuntu 14.04 LTS)
When I use firefox to create new article, the fields of the form overlap a bit. See the screen-shot:
http://screencloud.net/v/zS7o 

- [x] New article saves a draft always even if I didn't enter any thing.

- [x] Browser back button 
scenario: new article -> click back button -> the url changes to http://www.manshar.com/articles/new, but it keeps coming back to http://www.manshar.com/articles/SOMEID/edit (this also keeps creating new drafts, as mentioned in the previous point)

- [ ] http://www.manshar.com/articles/WRONG_ID/edit -> should show not found msg or something like this.

- [x] Go to an article and refresh the browser, the page comes out like this: 
   - [x] First, the side menu opens with an empty page, after a bit it closes.
   - [x] Then, the placeholder page appears, which I guess has the template but not the information yet (at this point I can see something like بقلم: غير معروف).
   - [x] After loading, the intended page comes out. 
   - [x] %% I guess showing a loading indicator or something like this and not opening the side menu would be more convenient. Or server rendering would be cooler.

- [x] One can notice that to load an article page 12 XHRs are issued (in case the user is logged in) which is too much. I am wondering, why do you need an OPTIONS req for each.

**Comment by ahmgeek** [comment]
Nice hunts :+1:

**Comment by mkhatib** [comment]
Thanks @qjouda 

Will investigate firefox bugs, we have few bugs already open for Firefox.

Autosaving a non-dirty article will be fixed in the next push.

All other points are valid and we'll be working on fixing them, thanks for pointing them out :bow: 

OPTIONS requests are made automatically by the browser when doing cross domain requests. Luckily they're heavily cached by the browsers so they will not be called again after the first time. The browser just needs to make sure this domain can make cross domain requests to the other. It might be worth investigating using a single domain with a path for apis instead (I think @mshamma mentioned something like that). But for now there are more urgent matters for performance that we're looking into.

Great points!

**Comment by mkhatib** [comment]
Auto-saving should only run on dirty check now.

**Comment by qjouda** [comment]
Cool. For the OPTIONS, it was my bad, I had the cache disabled so OPTIONS was firing every time!

**Comment by mkhatib** [comment]
Yup. Fell in the same mistake and had to investigate myself 😊

**Comment by mkhatib** [comment]
New design should have touched on some of the issues in this. Will file separate bug for the not-found page.
