### ISSUE TITLE
the used fonts are big

### ISSUE THREAD

**Issue by ahmedissa** [manshar/manshar#175]
the size of both files  (DroidNaskh-Regular / Bold) is more than 78 KB.
if we used base64, we can decrees the size to 5 KB!
i have done it locally but i am not sure if thats real number (from 78KB to 5KB). 
for converting from woff to base64 i used this tool (http://www.fontsquirrel.com/tools/webfont-generator)

**Comment by mkhatib** [comment]
Is this about the new WOFF 2.0 web font format? Or is it something else?

**Comment by ahmedissa** [comment]
i thought base64 done the compression, but the tool actually done that. 
the tool compressed the font (WOFF2) from 40KB to 2KB. 

http://www.fontsquirrel.com/tools/webfont-generator
the tool accepts only ttf fonts.

**Comment by mkhatib** [comment]
As I suspected this might be related to the new optimization with WOFF 2.0. Google event links to that tool in their recent blog posts about Web Fonts
http://googledevelopers.blogspot.com/2015/02/smaller-fonts-with-woff-20-and-unicode.html

Though I am not sure about the 2KB, it seems they have a table showing how much the saving is:

Font filename | None | GZIP | WOFF 2.0 | Improvement
------------ | ------------- | ------------ | ------------- | ------------
DroidNaskh-Bold.ttf | 94,620 | 53,197 | 40,760 | 23.38%
DroidNaskh-Regular.ttf | 91,340 | 50,955 | 38,892 | 23.67%


I actually just confirmed in fact that they are serving both in `font/woff2` content type format, so Manshar automatically got the compressed versions.

The reason why you are getting the 2KB is because it seems the default subset that the tool is including in the font doesn't include the Arabic subset letters and just includes a minimal subset of the english letters and so on. It is possible to select a subset that only includes what we need to use, but [Google Fonts blog post promises that they can do it automatically](http://googledevelopers.blogspot.com/2015/02/smaller-fonts-with-woff-20-and-unicode.html), and not sure how much of a difference would it make.

**Comment by ahmedissa** [comment]
You are right, the tool remove the Arabic subset.

**Comment by mkhatib** [comment]
This actually gave me an idea of saving tons on font-awesome. I realized we are only using a tiny fraction of font-awesome which its full size is >64KB. I used [Icomoon](https://icomoon.io/app/#/select/font) to select the exact icons we use now and download the subset and convert that using the site you sent to woff2 and now we'll be able to serve only 6KB instead of 64KB! 

Thanks for kicking this off! Will push code as soon as it passes!

**Comment by mkhatib** [comment]
Before:
![screen shot 2015-02-24 at 5 31 28 pm](https://cloud.githubusercontent.com/assets/2647/6365061/8723a0c0-bc65-11e4-8964-591710c74978.png)

After:
![screen shot 2015-02-24 at 8 40 07 pm](https://cloud.githubusercontent.com/assets/2647/6365063/8cd15e86-bc65-11e4-9ed3-9dbec2734b0e.png)
