### ISSUE TITLE
Words break among lines

### ISSUE THREAD

**Issue by HazemAM** [manshar/manshar#205]
Words can be broken as separate parts among consecutive lines if there is no space in the original line. This is due to the CSS property `word-wrap: break-word`, which is applied to the `#article-body` element.

**The problem is:** When deleting this property, the text flow gets all weird in some articles (in latest Chrome at least).

---

I found that the *real* problem is that text in `#article-body` uses `&nbsp;` (non-breaking space) as a space character **in some situations** (some paragraphs has 1 or 2, some has none, some are full of).

So, adding that CSS property solves this problem, but breaks other words as well.

---

A good example article of the whole problem: www.manshar.com/articles/2422.

**Comment by mkhatib** [comment]
I believe this has been fixed in our new design and new editor. We cleanup the text from unnecessary `&nbsp;`. Although the old article is still going to have the problem. I am hesitent about using `break-word` because it'll literally break the words into multiple lines.

Closing this for now, if you still see this in new articles and in the future please reopen.

**Comment by HazemAM** [comment]
Yes, `break-word` is indeed not the solution. Alright then, I'll keep an eye on that.
