### ISSUE TITLE
Contribution: Full separation 

### ISSUE THREAD

**Issue by saadshahd** [manshar/manshar#208]
The web-client is full separated. why I have to setup local backend, just wanna to contribute to the web-cient-app. this issue blocking me from contributing since three months every time I'm trying I got tired of backend setup and loose my passion.

Can you guys separate the contribution instructions to backend and web-client ?

**Comment by mkhatib** [comment]
@saadshahd thanks for filing this! This is a really good point! 

This is doable by doing couple of things, first setting up the `API_HOST` local environment variable to our remote endpoint `api-staging.manshar.com`. This is something you can easily do on your machine by running `export API_HOST=api-dev.manshar.com`.

The second thing we need is to deploy a dev instance of our backend that allows requests to be made from anywhere (instead of blocking cross-domain requests). 

I am currently working on deploying staging instances of the app, and will work on deploying a dev instance of the API so we can allow what you're asking for. Does that make sense?

**Comment by mkhatib** [comment]
@saadshahd I've just submitted a PR (#208) that adds `--api-host` flag to `grunt serve` and we've deployed a dev instance for people to run web-client locally against it.

If you pull the latest changes you can run the web client with:
```sh
grunt serve --api-host=api-dev.manshar.com
```

And this will run the web client without needing to run the backend. I've [documented this here](https://github.com/manshar/manshar/wiki/Contributing-to-Web-Client).

**Comment by saadshahd** [comment]
:+1: Now contributing is much easier. Thanks @mkhatib.
